service:
  name: s3-files-grouping-grouping
provider:
  stage: dev
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  memorySize: 128
  timeout: 16
  environment: ${file(./env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::s3-files-grouping-demo-bucket-${self:provider.stage}/*"
package:
  exclude:
    - '*.js'
    - '*.yml'
  include:
    - handler.js
  excludeDevDependencies: false
functions:
  group:
    handler: handler.group
    events:
      - s3:
          bucket: s3-files-grouping-demo-bucket-${self:provider.stage}
          event: s3:ObjectCreated:*
          rules:
            - prefix: upload/
